app.factory("townsList", function() {
	var towns = [
		{
			id: 1,
			name: "Castle",
			img: "/app/img/castle.jpg",
			descript: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <br>In a nisl vel turpis laoreet congue id porta metus. Sed malesuada fermentum ipsum sed tristique. <br>Vestibulum ac lectus nibh. Integer fermentum sollicitudin ex nec lobortis. Aliquam aliquam magna id dui finibus lacinia vitae ac tortor. Phasellus vehicula fermentum ligula in pretium. Donec in convallis dolor, lobortis lobortis magna. Phasellus orci felis, sollicitudin nec pulvinar ut, facilisis in lectus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis accumsan arcu tortor, a aliquet enim semper eget. Pellentesque finibus velit vitae consequat commodo. Integer non lobortis risus.Phasellus fermentum rutrum felis, nec varius nisl bibendum at. In ornare, dui quis placerat hendrerit, justo mi varius orci, ut ornare dui ipsum sed augue. Suspendisse commodo lacus lorem, in tempus enim auctor eget. Mauris condimentum sagittis tincidunt. Maecenas sed lacus varius, lobortis ligula id, semper odio. Aliquam erat volutpat. Etiam nec vestibulum ligula, id tempor ex. Aenean auctor ex eros, ut mattis velit fringilla consequat. Duis quis leo ac orci pharetra auctor et sit amet elit. Integer a dui ante. Sed elementum sapien finibus fermentum consequat. Phasellus dignissim tellus eu sem accumsan sollicitudin. Praesent elementum mollis lorem venenatis pretium. Sed molestie luctus sem, at dictum tortor pellentesque eget. Vestibulum convallis lacus a eleifend pharetra.</p>",
			value: "castle"
		},
		{
			id: 2,
			name: "Rampart",
			img: "/app/img/rampart.jpg",
			descript: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a nisl vel turpis laoreet congue id porta metus. Sed malesuada fermentum ipsum sed tristique. Vestibulum ac lectus nibh. Integer fermentum sollicitudin ex nec lobortis. Aliquam aliquam magna id dui finibus lacinia vitae ac tortor. Phasellus vehicula fermentum ligula in pretium. Donec in convallis dolor, lobortis lobortis magna. Phasellus orci felis, sollicitudin nec pulvinar ut, facilisis in lectus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis accumsan arcu tortor, a aliquet enim semper eget. Pellentesque finibus velit vitae consequat commodo. Integer non lobortis risus. Phasellus fermentum rutrum felis, nec varius nisl bibendum at. In ornare, dui quis placerat hendrerit, justo mi varius orci, ut ornare dui ipsum sed augue. Suspendisse commodo lacus lorem, in tempus enim auctor eget. Mauris condimentum sagittis tincidunt. Maecenas sed lacus varius, lobortis ligula id, semper odio. Aliquam erat volutpat. Etiam nec vestibulum ligula, id tempor ex. Aenean auctor ex eros, ut mattis velit fringilla consequat. Duis quis leo ac orci pharetra auctor et sit amet elit. Integer a dui ante. Sed elementum sapien finibus fermentum consequat. Phasellus dignissim tellus eu sem accumsan sollicitudin. Praesent elementum mollis lorem venenatis pretium. Sed molestie luctus sem, at dictum tortor pellentesque eget. Vestibulum convallis lacus a eleifend pharetra. Nam sed eros et nunc porta dictum et dictum leo. Ut a neque ac sapien feugiat eleifend sed eget mauris. Pellentesque fringilla nulla metus, vel fringilla libero lobortis vel. Phasellus lobortis sagittis finibus. Pellentesque condimentum ante diam. Donec eget sodales enim. Nunc a pulvinar orci. Nulla urna eros, finibus sit amet sapien vitae, pulvinar venenatis felis. Fusce odio metus, lacinia ut ullamcorper at, dapibus nec ipsum. Nam suscipit vitae quam ac placerat. Nunc eu mi vulputate, semper diam quis, vehicula lacus. Pellentesque sagittis nibh quis mi placerat viverra. Sed eget imperdiet nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
			value: "rampart"
		}
	];
	return towns;
});